### PR TITLE
Add github workflows to perform clippy checks, formatting and tests

### PR DESCRIPTION
**Pull request by x4e**
I also performed some cleanups to ensure that the tests pass.

This might make some conflicts with the active PRs (especially #22).
Best way to resolve this would be to merge the workflows in and discard the rest of the changes.
Then manually fix the errors given. 
You can also run `cargo fmt` and `cargo clippy -- -D warnings -A clippy::upper_case_acronyms` locally so you don't need to wait for the workflow.

### CODE REVIEW

**Comment by x4e** [comment]
Added a .editorconfig file to help ides

**Comment by willemml** [comment]
This looks good, might be worth adding a git pre-commit hooks for fmt and clippy though, but I can do that later...
Thanks though, I have been wondering about the Actions flows for a while now...

**Comment by willemml** [comment]
I also tried merging with #22 locally, many conflicts so I will have to merge and then discard I guess.

**Comment by x4e** [comment]
I don't really like pre-commit hooks, I think workflow is fine because if anyone pushes their changes to a fork or creates a pull request it will be very visible, but your choice

**Comment by x4e** [comment]
And yeah, just discard all of the changes this has made to .rs files when merging

**Comment by willemml** [comment]
> I don't really like pre-commit hooks, I think workflow is fine because if anyone pushes their changes to a fork or creates a pull request it will be very visible, but your choice

Ahh, I see what you mean now, yeah, this is fine, thanks!


> And yeah, just discard all of the changes this has made to .rs files when merging

Yeah, I'll do that then

**Review by willemml — APPROVED** [review]

**Comment by fee1-dead** [comment]
Have you seen https://github.com/actions-rs/clippy-check? It's a nice addition to what you have here.

**Comment by willemml** [comment]
I haven't seen that, it looks really cool though, might add it. Thanks!

**Comment by x4e** [comment]
Thats very cool, thanks for sharing @fee1-dead

**Pull request merged**
