### PR TITLE
Merge actions into one action

### PR DESCRIPTION
**Pull request by x4e**

### CODE REVIEW

**Comment by x4e** [comment]
The action is failing not due to issues with the action but issues with the source code that can be resolved separately to this pr.

```
error: redundant field names in struct initialization
   --> src/auth.rs:309:13
    |
309 |             id: id,
    |             ^^^^^^ help: replace it with: `id`
    |
    = note: `-D clippy::redundant-field-names` implied by `-D warnings`
    = help: for further information visit rust-lang.github.io/rust-clippy/master/index.html#redundant_field_names

error: redundant field names in struct initialization
   --> src/auth.rs:310:13
    |
310 |             token: token,
    |             ^^^^^^^^^^^^ help: replace it with: `token`
    |
    = help: for further information visit rust-lang.github.io/rust-clippy/master/index.html#redundant_field_names

error: redundant field names in struct initialization
   --> src/graphql_model.rs:324:21
    |
324 |                     query: query,
    |                     ^^^^^^^^^^^^ help: replace it with: `query`
    |
    = help: for further information visit rust-lang.github.io/rust-clippy/master/index.html#redundant_field_names

error: this `if` statement can be collapsed
   --> src/hub.rs:294:24
    |
294 |                   } else if value == &None {
    |  ________________________^
295 | |                     if self.has_permission(&permission.into()) {
296 | |                         return true;
297 | |                     }
298 | |                 }
    | |_________________^
    |
    = note: `-D clippy::collapsible-if` implied by `-D warnings`
    = help: for further information visit rust-lang.github.io/rust-clippy/master/index.html#collapsible_if
help: collapse nested if block
    |
294 |                 } else if value == &None && self.has_permission(&permission.into()) {
295 |                     return true;
296 |                 }
    |

error: this `else { if .. }` block can be collapsed
   --> src/hub.rs:453:16
    |
453 |           } else {
    |  ________________^
454 | |             if let Some(user) = self.members.get(user_id) {
455 | |                 check_permission!(user, channel_id, ChannelPermission::Read, self);
456 | |                 check_permission!(user, channel_id, ChannelPermission::Configure, self);
...   |
464 | |             }
465 | |         }
    | |_________^
    |
    = note: `-D clippy::collapsible-else-if` implied by `-D warnings`
    = help: for further information visit rust-lang.github.io/rust-clippy/master/index.html#collapsible_else_if
help: collapse nested if block
    |
453 |         } else if let Some(user) = self.members.get(user_id) {
454 |             check_permission!(user, channel_id, ChannelPermission::Read, self);
455 |             check_permission!(user, channel_id, ChannelPermission::Configure, self);
456 |             if let Some(channel) = self.channels.get_mut(channel_id) {
457 |                 Ok(mem::replace(&mut channel.description, new_description))
458 |             } else {
  ...
  ```

**Comment by willemml** [comment]
Awesome, thanks! The checks that fail here are now fixed in #22 and not fixing them here prevents conflicts that would arise when merging it.

**Comment by fee1-dead** [comment]
It should be fixed in master and merged in the `gpg` branch

**Comment by willemml** [comment]
Bit too late for that, but yeah, just would have been painful due to the huge number of conflicts, and `gpg` will be in master soon anyways.

**Pull request merged**
